#! /bin/sh

echo "save_quicklook $1" 
echo "save_data: $2"
echo "save_netCDF: $3"
echo "save_catalog: $4"
echo "near range (0=off,1=on): $5"
echo "afterpulse correction (0=off, 1=on): $6" 
echo "node: $7"
node=\'$7\'
echo "node = ${node}"
daystr=\'$8\'
echo "daystr = ${daystr}"

# get current date and year to feed into Matlab
# daystr=`date -u +%y%m%d`
# year=`date +%Y`
# if the first 20 min of a new day use previous day 
# hour=`date -u +%k%M` 
# echo "hour = $hour"
# if [ $hour -lt 20 ]
# then 
# echo finish processing previous day
# daystr=`date +%y%m%d`
# fi
# echo "daystr = $daystr"
# echo "year = $year"

# make output dirs
# mkdir -p /scr/eldora1/wvdial_1_processed_data
# mkdir -p /scr/eldora1/wvdial_2_processed_data

# set the Matlab command
 matcmd="addpath /home/rsfdata/Processing/EOL_Lidar_Matlab_Processing; DIAL_process_NetCDF_function($1,$2,$3,$4,$5,$6,${node},${daystr}); exit"
# save_quicklook, save_data, save_netCDF, save_catalog, near, afterpulse, node, daystring(file to process)
 cmd="/opt/local/bin/matlab -nodisplay -nosplash -r \"$matcmd\""
# cmd="/opt/local/bin/matlab -r \"$matcmd\""
 echo "cmd = $cmd"
# run the command
 eval $cmd
