%% Import data from text file
% Script for importing data from the following text file:
%
%    filename: /Users/spuler/Desktop/Hunidity Test/weather_station/20200930/WeatherStation_04_20200930_000000.txt
%
% Auto-generated by MATLAB on 06-Nov-2020 08:42:59

%% Setup the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 5);

% Specify range and delimiter
opts.DataLines = [1, Inf];
opts.Delimiter = " ";

% Specify column names and types
opts.VariableNames = ["VarName1", "VarName2", "VarName3", "VarName4", "VarName5"];
opts.VariableTypes = ["double", "double", "double", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";
opts.ConsecutiveDelimitersRule = "join";
opts.LeadingDelimitersRule = "ignore";

% Import the data
WS_30 = readtable("/Users/spuler/Desktop/Hunidity Test/weather_station/20201001/WeatherStation_04_20201001_060000.txt", opts);

%% Convert to output type
WS_30 = table2array(WS_30);

%% Clear temporary variables
clear opts